@environment=local
@controller=Syllabuses
@base_url=https://localhost:5000/api/
@access_token=https://localhost:5000/api/
@id=https://localhost:5000/api/
# Get all syllabuses
GET {{base_url}}/{{controller}} HTTP/1.1
Host: localhost:5000
{{access_token}}

###

# Get syllabus by ID
GET {{base_url}}/{{controller}}/{{id}} HTTP/1.1

###

# Create a new syllabus
POST {{base_url}}/{{controller}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "property1": "value1",
  "property2": "value2"
}

###

# Update an existing syllabus
PUT {{base_url}}/{{controller}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "id": 1,
  "property1": "updatedValue1",
  "property2": "updatedValue2"
}

###

# Delete a syllabus
DELETE {{base_url}}/{{controller}}/{{id}} HTTP/1.1
Authorization: Bearer {{access_token}}

###

# Export syllabuses to CSV
GET {{base_url}}/{{controller}}/export-syllabuses-csv?columnSeparator=comma HTTP/1.1

###

# Import syllabuses from CSV
POST {{base_url}}/{{controller}}/import-syllabuses-csv?IsScanCode=true&IsScanName=true&DuplicateHandle=Replace HTTP/1.1
Content-Type: multipart/form-data
Authorization: Bearer {{access_token}}

###

# Get paged syllabuses by date range
GET {{base_url}}/{{controller}}/get-paged-syllabuses-by-date-range?fromtDate=2023-01-01&toDate=2023-12-31&pageIndex=0&pageSize=10 HTTP/1.1
