export const apiUrl =
  process.env.NODE_ENV !== "production" 
  ? "https://trainingmanagementsystem2.azurewebsites.net/api/"
    // ? "https://localhost:5001/api/"
    : "https://trainingmanagementsystem2.azurewebsites.net/api/";
// https://cryptic-oasis-02805.herokuapp.com/api/  http://localhost:5000/api/
export const LOCAL_STORAGE_TOKEN_NAME = "systemManager";

//ActionPost
export const POSTS_LOADED_SUCCESS = "POSTS_LOADED_SUCCESS";
export const POSTS_LOADED_FAIL = "POSTS_LOADED_FAIL";
export const ADD_POST = "ADD_POST";
export const DELETE_POST = "DELETE_POST";
export const UPDATE_POST = "UPDATE_POST";
export const FIND_POST = "FIND_POST";

//Action Syllbus

export const SYLLABUS_LOADED_SUCCESS = "SYLLABUS_LOADED_SUCCESS";
export const SYLLABUS_LOADED_FAIL = "SYLLABUS_LOADED_FAIL";
export const ADD_SYLLABUS = "ADD_POST";
export const DELETE_SYLLABUS = "DELETE_SYLLABUS";
export const UPDATE_SYLLABUS = "UPDATE_SYLLABUS";
export const FIND_SYLLABUS = "FIND_SYLLABUS";
export const SET_STATE = "SET_STATE";
export const FIND_SYLLABUS_DETAIL = "FIND_SYLLABUS_DETAIL";
export const ADD_SYLLABUS_UNIT = "ADD_SYLLABUS_DETAIL";
export const UPDATE_SYLLABUS_UNIT = "UPDATE_SYLLABUS_DETAIL";
export const DELETE_SYLLABUS_UNIT = "DELETE_SYLLABUS_DETAIL";
export const ADD_SYLLABUS_LESSON = "ADD_SYLLABUS_LESSON";
export const UPDATE_SYLLABUS_LESSON = "UPDATE_SYLLABUS_LESSON";
export const DELETE_SYLLABUS_LESSON= "DELETE_SYLLABUS_LESSON";
export const ADD_SYLLABUS_MATERIAL = "ADD_SYLLABUS_MATERIAL";
export const UPDATE_SYLLABUS_MATERIAL = "UPDATE_SYLLABUS_MATERIAL";
export const DELETE_SYLLABUS_MATERIAL= "DELETE_SYLLABUS_MATERIAL";
export const IMPORT_SYLLABUS_FILE= "IMPORT_SYLLABUS_FILE";











//Action training program
export const TRAINING_PROGRAM_LOADED_SUCCESS = "TRAINING_PROGRAM_LOADED_SUCCESS";
export const TRAINING_PROGRAM_TEST_FILE_GET_SUCCESS = "TRAINING_PROGRAM_TEST_FILE_GET_SUCCESS";
export const TRAINING_PROGRAM_GET_SUCCESS = "TRAINING_PROGRAM_GET_SUCCESS";
export const TRAINING_PROGRAM_LOADED_FAIL = "TRAINING_PROGRAM_LOADED_FAIL";
export const ADD_TRAINING_PROGRAM = "ADD_TRAINING_PROGRAM";
export const DELETE_TRAINING_PROGRAM = "DELETE_TRAINING_PROGRAM";
export const UPDATE_TRAINING_PROGRAM = "UPDATE_TRAINING_PROGRAM";
export const FIND_TRAINING_PROGRAM = "FIND_TRAINING_PROGRAM";

//Action training class
export const TRAINING_CLASS_LOADED_SUCCESS = "TRAINING_CLASS_LOADED_SUCCESS";
export const TRAINING_CLASS_GET_SUCCESS = "TRAINING_CLASS_GET_SUCCESS";
export const TRAINING_CLASS_LOADED_FAIL = "TRAINING_CLASS_LOADED_FAIL";
export const ADD_TRAINING_CLASS = "ADD_TRAINING_CLASS";
export const DELETE_TRAINING_CLASS = "DELETE_TRAINING_CLASS";
export const UPDATE_TRAINING_CLASS = "UPDATE_TRAINING_CLASS";
export const FIND_TRAINING_CLASS = "FIND_TRAINING_CLASS";
export const TRAINING_CLASS_GET_STUDENTGPA_SUCCESS = "TRAINING_CLASS_GET_STUDENTGPA_SUCCESS";
export const DELETE_TESTASSESSMENT = "DELETE_TESTASSESSMENT";


//Action User 
export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const USER_GET_SUCCESS = "USER_GET_SUCCESS";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";
export const ADD_USER = "ADD_USER";
export const DELETE_USER = "DELETE_USER";
export const UPDATE_USER = "UPDATE_USER";
export const FIND_USER = "FIND_USER";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const STUDENT_GET_CLASSGPA_SUCCESS = "STUDENT_GET_CLASSGPA_SUCCESS";
export const UPDATE_ATTENDANCE = "UPDATE_ATTENDANCE";
export const SET_ROLE = "SET_ROLE";



